language: go
go_import_path: github.com/vlifesystems/rulehunter
sudo: required

go:
  - 1.8
  - tip

services:
  - mysql

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  #- go get github.com/lawrencewoodman/roveralls
  - pwd=`pwd`
  - cd $HOME/gopath/src
  - mkdir -p lawrencewoodman
  - cd lawrencewoodman
  - git clone github.com/lawrencewoodman/roveralls
  - cd roveralls
  - git checkout v7
  - go build
  - go install
  - cd $pwd
  - mysql < ci/createflow_travis.sql

script:
  - chmod +x linux-test-su.sh
  - sudo ./linux-test-su.sh $GOPATH `which go` upstart
  - pwd
  - go test -covermode=count -coverprofile=profile.coverprofile
  - ls -la profile.coverprofile
  - cat profile.coverprofile
  - $HOME/gopath/bin/roveralls -v
  - $HOME/gopath/bin/goveralls -coverprofile=roveralls.coverprofile -service=travis-ci
  - cd examples
  - chmod +x bin/init_www_unix.sh
  - bin/init_www_unix.sh
  - rulehunter --config=config_quick.yaml
