language: go

go:
  - 1.6
  - tip

services:
  - mysql

before_install:
  - echo $PATH
  - ls /usr/bin/systemctl
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/lawrencewoodman/roveralls
  - mysql < ci/createflow_travis.sql

script:
  - chmod +x linux-test-su.sh
  - sudo ./linux-test-su.sh $GOPATH `which go`
  - $HOME/gopath/bin/roveralls
  - $HOME/gopath/bin/goveralls -coverprofile=roveralls.coverprofile -service=travis-ci
