version: "{build}"

platform:
  - x86
  - x64

clone_folder: c:\gopath\src\github.com\vlifesystems\rulehuntersrv

environment:
  GOPATH: c:\gopath

install:
   # pre-installed MinGW at C:\MinGW is 32bit only
   # but MSYS2 at C:\msys64 has mingw64
  - IF "%PLATFORM%" == "x86" (set PATH="C:\mingw\bin;%PATH%")
  - IF "%PLATFORM%" == "x64" (set PATH="C:\msys64\mingw64\bin;%PATH%")
  - echo %PATH%
  - go version
  - go env

build_script:
  - go get -v -t ./...

test_script:
  - go test -v ./...
