version: "{build}"

platform:
  - x86
  - x64

clone_folder: c:\gopath\src\github.com\vlifesystems\rulehuntersrv

environment:
  GOPATH: c:\gopath

install:
  - ps: |
      if ($env:PLATFORM -eq "x64") {
        # pre-installed MinGW at C:\MinGW is 32bit only
        # but MSYS2 at C:\msys64 has mingw64
        setx MINGWPATH "C:\msys64\mingw64\bin"
      } else {
        setx MINGWPATH "C:\mingw\bin"
      }
  - set PATH="%MINGWPATH%;%PATH%"
  - echo %PATH%
  - go version
  - go env

build_script:
  - go get -v -t ./...

test_script:
  - go test -v ./...
